#!/usr/bin/env python3
def hello():
    """Print Hello World in random colors"""
    import skilstak.colors as c
    print(c.cl + c.rc() + "Hello " + c.rc() + "World!" + c.x)


if __name__ == '__main__':
    hello()
                                                                                                                                         
