#!/usr/bin/env python3
import skilstak.colors as c

def print_colored(word):
    """Prints each character in random color
    Args:
            
    """
    for char in word:
        print(c.rc() + char + c.x, end = '')

def colored_hello():
    """Print Hello World to the console with each character a random color."""
    try:
        print(c.clear)
        while True:
            print_colored("Hello world!")
    except KeyboardInterrupt:
        exit()
def hello():
    """Print Hello World to the console in random colors"""
    while True:
        print(c.cl + c.rc() + "Hello " + c.rc() + "World!" + c.x)


if __name__ == '__main__':
    import sys
    if len (sys.argv) > 1 and sys.argv[1].startswith("c"):
        colored_hello()
    if len(sys.argv) == 1:
        hello()
    else:
        hello(sys.argv[1])
                                                                                                                                         
