#!/usr/bin/env node

'use strict';
//console.log("Hello World")
var out = process.stdout;
var c = require('skilstak-colors');
while (true) {
  out.write(c.rc() + "Hello " + c.rc() + "World! " + c.x);
  };
